### ISSUE TITLE
LLaMA-2 w/o RAG result + training on wiki

### ISSUE THREAD

**Issue by xstgavin** [xsc1234/INFO-RAG#1]
Hi 
May I know what is the result of LLaMa-2 w/o RAG + training on wiki? To help us study  if its own knowledge is good enough to answer all question after tuning with wiki. 
thx a lot.

**Comment by xsc1234** [comment]
Thanks for your attention! We did not conduct this experiment. Because LLama-2 has been pre-trained on a large amount of wiki data, we think w/o + training on wiki will not bring effective improvements. 
Thanks :)
