### ISSUE TITLE
Request for Code Release

### ISSUE THREAD

**Issue by LWL-cpu** [xsc1234/INFO-RAG#3]
I hope this message finds you well. I recently came across your paper and found your work incredibly insightful and relevant to my current research. I understand from your repository that you plan to release the code upon the paper's acceptance. Since I am keenly interested in your work, I wanted to kindly inquire if there has been any update on the paper's status and the potential timeline for the code release. 

Thank you very much~

**Comment by xsc1234** [comment]
Thanks for your attention. We promise to release code before June 15th.
