### ISSUE TITLE
Evaluation的代码

### ISSUE THREAD

**Issue by LWL-cpu** [xsc1234/INFO-RAG#5]
您好，请问有没有评测的代码呢。

**Comment by LWL-cpu** [comment]
您好，请问code generation评测的prompt是怎么设置的呢？我用llama3-8b直接评测CodeXGLUE的效果非常差，请问可以开源下你们使用的prompt吗，万分感谢！

**Comment by gitccl** [comment]
哈喽老哥，请问一下你复现论文中的效果了吗

**Comment by xsc1234** [comment]
您好，感谢关注，关于Code Generation的评测，请确保您按照以下步骤进行：

1. 使用正确的[SCODE-R](https://github.com/rizwan09/REDCODER) 检索模型。
2. 以CodeSearchNET为检索语料库，你也可以直接使用SCODE-R提供的检索好了的列表
3. 我们的CodeBlue evaluation脚本可以在这里访问[evaluation_scripts](https://github.com/rizwan09/REDCODER/tree/main/SCODE-G/evaluation_scripts)
4. 针对LlaMA-2-13B-chat的prompt (python) 为：
```
Retrieved_texts = '[REFERENCE] number {}: {}'.format(idx, code)

[INST] \n\n" + Retrieved_texts + ' Give me the python code to achieve this function according to the [REFERENCE] texts: ' + question + " [/INST]
```

**Comment by gitccl** [comment]
> 您好，感谢关注，关于Code Generation的评测，请确保您按照以下步骤进行：
> 
> 1. 使用正确的[SCODE-R](https://github.com/rizwan09/REDCODER) 检索模型。
> 2. 以CodeSearchNET为检索语料库，你也可以直接使用SCODE-R提供的检索好了的列表
> 3. 我们的CodeBlue evaluation脚本可以在这里访问[evaluation_scripts](https://github.com/rizwan09/REDCODER/tree/main/SCODE-G/evaluation_scripts)
> 4. 针对LlaMA-2-13B-chat的prompt (python) 为：
> 
> ```
> Retrieved_texts = '[REFERENCE] number {}: {}'.format(idx, code)
> 
> [INST] \n\n" + Retrieved_texts + ' Give me the python code to achieve this function according to the [REFERENCE] texts: ' + question + " [/INST]
> ```

哈喽，请问一下有QA评测的步骤和prompt吗

**Comment by LWL-cpu** [comment]
感谢您的回复！
